// <auto-generated />
using CrudProjectJpv.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudProjectJpv.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrudProjectJpv.Models.CadastroPessoa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cpf")
                        .HasColumnType("int")
                        .HasColumnName("cpf");

                    b.Property<int>("dataNascimento")
                        .HasColumnType("int")
                        .HasColumnName("dataNascimento");

                    b.Property<string>("nomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nomeCompleto");

                    b.Property<decimal>("valorRenda")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorRenda");

                    b.HasKey("id");

                    b.ToTable("CadastroPessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
